### ISSUE TITLE
发现错误，以及能否开启多线程上传下载

### ISSUE THREAD

**Issue by krmao** [paper/gulp-tinypng-nokey#4]
```
[16:26:58] gulp-tinypng-nokey : [compressing] Ok nc_share.png (33.7%)
[16:26:58] gulp-tinypng-nokey : [tinypng request] nc_title.png
[16:27:06] 'buildImagesTask' errored after 4.73 min
[16:27:06] SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at Request._callback (/node_modules/gulp-tinypng-nokey/index.js:89:28)
    at Request.self.callback (/node_modules/gulp-tinypng-nokey/node_modules/request/request.js:123:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/node_modules/gulp-tinypng-nokey/node_modules/request/request.js:893:14)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/node_modules/gulp-tinypng-nokey/node_modules/request/request.js:844:12)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
[16:27:06] 'build' errored after 4.73 min
[16:27:06] The following tasks did not complete: <series>, <parallel>, buildImagesTask
[16:27:06] Did you forget to signal async completion?

```

**Comment by maksymdavydchuk** [comment]
The same

**Comment by yordanzhelevdev** [comment]
Same

**Comment by yordanzhelevdev** [comment]
This happens because sometimes the server responds with HTML.

```
"\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n"
undefined:2
```

**Comment by yordanzhelevdev** [comment]
That happens because the server sometimes return HTML 

````
"\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n"
undefined:2
````
